
= Variability-aware APOC 4.3.x



== Introduction

// tag::intro-text[]
Neo4j 3.x introduced the concept of user-defined procedures and functions.
Those are custom implementations of certain functionality, that can't be (easily) expressed in Cypher itself.
They are implemented in Java and can be easily deployed into your Neo4j instance, and then be called from Cypher directly.

The APOC library consists of many (about 450) procedures and functions to help with many different tasks in areas like data integration, graph algorithms or data conversion.
// end::intro-text[]

=== License

Apache License 2.0

=== Detailed Feature Documentation

See the link https://neo4j.com/labs/apoc/4.3/[APOC User Guide^] for documentation of each of the major features of the library, including data import/export, graph refactoring, data conversion, and more.

== Manual Installation

Since APOC relies on Neo4j's internal APIs you need to use the *matching APOC version* for your Neo4j installaton.
Make sure that the *first two version numbers match between Neo4j and APOC*.

You can find http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/[all releases here].

// tag::version-matrix[]
=== Version Compatibility Matrix

Since APOC relies in some places on Neo4j's internal APIs you need to use the right APOC version for your Neo4j installaton.

APOC uses a consistent versioning scheme: `<neo4j-version>.<apoc>` version. 
The trailing `<apoc>` part of the version number will be incremented with every apoc release.

[opts=header]
|===
|apoc version | neo4j version
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.0.0.16[4.0.0.16#^] | 4.0.6 (4.0.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.5.0.11[3.5.0.11^] | 3.5.16 (3.5.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.4.0.4[3.4.0.6^] | 3.4.12 (3.4.x)
| http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.3.0.4[3.3.0.4^] | 3.3.6 (3.3.x)
|===

// end::version-matrix[]
=== Get APOC Version

To know your current `apoc` version you can use the *function* :

[source,cypher]
----
RETURN apoc.version();
----

== Build & install the current development branch from source

----
git clone https://github.com/echo-xiangchen/apoc-aware.git
cd apoc-aware
./gradlew shadow
----
*Copy the file named `apoc-aware-4.3.0.2-all.jar`(in `apoc-aware/full/build/libs/`) into your `$NEO4J_HOME/plugins/` folder*, then restart your neo4j database.

// If you want to run embedded or use neo4j-shell on a disk store, configure your `plugins` directory in `conf/neo4j.conf` with `dbms.plugin.directory=path/to/plugins`.

A full build including running the tests can be run by `./gradlew build`.

// end::build[]

== Configuration file setting
For properly calling APOC procedures and functions, *you need to add several lines to the file `neo4j.conf`(in Neo4j Desktop, you only need to add these lines in `Settings` for the database)*:

----
# APOC settings
## For reading from files you’ll have to enable the config option:
apoc.import.file.enabled=true

## By default file paths are global, for paths relative to the import directory set:
apoc.import.file.use_neo4j_config=true

## By default exporting to the file system is disabled. We can enable it by setting the following property:
## The export file will be saved in "import" folder
apoc.export.file.enabled=true
----

== Example
Following are some examples using this modified APOC library.

=== Importing CSV files into Neo4j database
For importing CSV files, here we use `apoc.import.csv`, you could use `LOAD` clause in Cypher directly. +

If you have two CSV files, one contains the nodes and the other contains the relationship, named `node.csv` and `relationship.csv` respectively. *Put them in the `import` folder* and make sure *they follow the CSV header format* in https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/#import-tool-header-format[here^]. +

Use the following procedure:
----
CALL apoc.import.csv(
  [{fileName: 'nodes.csv', labels: []}],
  [{fileName: 'edges.csv', type: ''}],
  {delimiter: '\t'});
----
Detailed configurations of `apoc.import.csv` can be found https://neo4j.com/labs/apoc/4.3/import/import-csv/[here^].

=== Querying the graph in Neo4j
For example, if you want to query a pattern that a function calls another function directly or indirectly (e.g., function A calls function B, and function B calls function C, then A->C will also be included), you could use the following query:
----
MATCH (p:func)
CALL apoc.aware.path.expandConfig(p, {
    relationshipFilter: 'CALL>',
    labelFilter: '>func'
})
YIELD path RETURN path, length(path) AS hops
ORDER BY hops
----
`apoc.aware.path.expandConfig` is the modified version of `apoc.path.expandConfig` (`apoc.path.expandConfig` remains unchanged, you could use it as normal). Their syntax is the same, except that `apoc.aware.path.expandConfig` *will evaluate each intermidiate result, and eliminate those do not satisfy the SAT check* (i.e., the big conjunction of PCs along the path is not satisfiable). 

Detailed configurations of `apoc.path.expandConfig` and other advanced graph querying procedures can be found https://neo4j.com/labs/apoc/4.3/graph-querying/path-expander/[here^]

=== Exporting results to a CSV file
You could also export the result as a CSV file, using `apoc.export.csv.query`:
----
WITH "MATCH (p:func)
CALL apoc.path.expandConfig(p, {
    labelFilter: '>func'
})
YIELD path RETURN DISTINCT path, length(path) AS hops
ORDER BY hops" AS query
CALL apoc.export.csv.query(query, "paths.csv", {})
YIELD file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
RETURN file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data;
----
Detailed configurations of `apoc.export.csv.query` and other exporting CSV procedures can be found https://neo4j.com/labs/apoc/4.3/export/csv/[here^].
